lines = [
    "import structlog",
    "import threading",
    "import time",
    "import numpy as np",
    "",
    "from .ring_buffer import AudioRingBuffer",
    "from .event_bus import EventBus",
    "from .mic_capture import MicCaptureThread",
    "from .vad_engine import SileroVAD, SpeechSegmentQueue",
    "from .stt_engine import StreamingSTTEngine",
    "from .tts_engine import PiperTTSEngine",
    "",
    "logger = structlog.get_logger()",
    "",
    "class VoiceSessionManager:",
    "    def __init__(self, event_bus: EventBus):",
    "        self.bus = event_bus",
    "        self.is_active = False",
    "",
    "        self.ring_buffer = AudioRingBuffer(buffer_seconds=15)",
    "        self.mic = MicCaptureThread(self.ring_buffer)",
    "        self.vad = SileroVAD()",
    "        self.stt = StreamingSTTEngine()",
    "        self.tts = PiperTTSEngine()",
    "        ",
    "        self.tts.on_playback_start = self._tts_start_callback",
    "        self.tts.on_playback_end = self._tts_end_callback",
    "        ",
    "        self.speech_queue = SpeechSegmentQueue()",
    "        self._orchestrator_thread = None",
    "        self._watchdog_thread = None",
    "        self._tts_buffer = ''",
    "        self._last_tts_end_time = 0",
    "        self._fft_ema_bands = np.zeros(12)",
    "",
    "    def _tts_start_callback(self):",
    "        self.bus.publish('voice_events', 'TTS_START')",
    "        if self.is_active:",
    "            self.mic.stop()",
    "            ",
    "    def _tts_end_callback(self):",
    "        self._last_tts_end_time = time.time()",
    "        self.bus.publish('voice_events', 'TTS_END')",
    "        if self.is_active:",
    "            self.bus.publish('voice_events', 'LISTENING')",
    "            self.mic.start()",
    "        else:",
    "            self.bus.publish('voice_events', 'VOICE_MODE_OFF')",
    "",
    "    def _handle_voice_events(self, event):",
    "        etype = event.get('type')",
    "        data = event.get('data', {})",
    "        ",
    "        if etype == 'AI_STREAM':",
    "            text_chunk = data.get('text', '')",
    "            if text_chunk.startswith('{'):",
    "                import json",
    "                try:",
    "                    parsed = json.loads(text_chunk)",
    "                    if 'response' in parsed:",
    "                        text_chunk = parsed['response']",
    "                except:",
    "                    pass",
    "                    ",
    "            self._tts_buffer += text_chunk",
    "            ",
    "            import re",
    "            while True:",
    "                match = re.search(r'([.!?\n]+)(?:\s|$)', self._tts_buffer)",
    "                if match:",
    "                    split_idx = match.end()",
    "                    sentence = self._tts_buffer[:split_idx].strip()",
    "                    self._tts_buffer = self._tts_buffer[split_idx:]",
    "                    if len(sentence) > 1:",
    "                        if '?' in sentence:",
    "                            sentence = f'<prosody pitch=\'+10%\'>{sentence}</prosody>'",
    "                        elif '!' in sentence:",
    "                            sentence = f'<prosody rate=\'fast\' volume=\'loud\'>{sentence}</prosody>'",
    "                        self.play_tts(sentence)",
    "                else:",
    "                    if len(self._tts_buffer) > 60 and ',' in self._tts_buffer:",
    "                        split_idx = self._tts_buffer.rfind(',') + 1",
    "                        sentence = self._tts_buffer[:split_idx].strip()",
    "                        self._tts_buffer = self._tts_buffer[split_idx:]",
    "                        if len(sentence) > 1:",
    "                            self.play_tts(sentence)",
    "                    break",
    "                    ",
    "        elif etype == 'AI_DISPATCH_COMPLETE':",
    "            buffer_to_play = self._tts_buffer.strip()",
    "            self._tts_buffer = ''",
    "            if len(buffer_to_play) > 1:",
    "                self.play_tts(buffer_to_play, is_final=True)",
    "            else:",
    "                self.play_tts('', is_final=True)",
    "",
    "    def start(self):",
    "        if self.is_active: return",
    "        self.is_active = True",
    "        self.mic.start()",
    "        ",
    "        self.bus.publish('voice_events', 'VOICE_MODE_ON')",
    "        self.bus.publish('voice_events', 'LISTENING')",
    "",
    "        self._orchestrator_thread = threading.Thread(target=self._run_pipeline, daemon=True)",
    "        self._orchestrator_thread.start()",
    "        ",
    "        self._watchdog_thread = threading.Thread(target=self._run_watchdog, daemon=True)",
    "        self._watchdog_thread.start()",
    "        ",
    "        self.bus.publish('system_events', 'READY')",
    "        logger.info('VoiceSessionManager active.')",
    "",
    "    def _run_watchdog(self):",
    "        import psutil",
    "        while self.is_active:",
    "            cpu = psutil.cpu_percent(interval=1)",
    "            mem = psutil.virtual_memory().percent",
    "            if cpu > 90 or mem > 90:",
    "                self.bus.publish('system_events', 'RESOURCE_WARNING', {'cpu': cpu, 'mem': mem})",
    "            time.sleep(5)",
    "",
    "    def stop(self):",
    "        if not self.is_active: return",
    "        self.is_active = False",
    "        self.mic.stop()",
    "        self.tts.clear_queue()",
    "        self.bus.publish('voice_events', 'VOICE_MODE_OFF')",
    "        logger.info('VoiceSessionManager dismantled.')",
    "",
    "    def _run_pipeline(self):",
    "        sample_rate = 16000",
    "        vad_frame_size = 512",
    "        ",
    "        in_speech = False",
    "        speech_start_time = 0",
    "        silence_dur = 0",
    "        current_speech_idx = 0",
    "        ",
    "        MAX_SILENCE_MS = 800",
    "        MAX_SILENCE_FRAMES = int((MAX_SILENCE_MS / 1000.0) * sample_rate / vad_frame_size)",
    "        ",
    "        partial_history = []",
    "        stable_count = 0",
    "        last_stable_text = ''",
    "        ",
    "        last_read_idx = self.ring_buffer.write_index",
    "        local_audio_buffer = np.zeros(0, dtype=np.float32)",
    "        vad_state_is_speech = False",
    "        silence_frame_count = 0",
    "",
    "        while self.is_active:",
    "            time.sleep(0.01)",
    "            ",
    "            current_write_idx = self.ring_buffer.write_index",
    "            if current_write_idx == last_read_idx:",
    "                continue",
    "                ",
    "            with self.ring_buffer._lock:",
    "                if current_write_idx > last_read_idx:",
    "                    new_samples = self.ring_buffer.buffer[last_read_idx:current_write_idx].copy()",
    "                else:",
    "                    new_samples = np.concatenate((",
    "                        self.ring_buffer.buffer[last_read_idx:].copy(),",
    "                        self.ring_buffer.buffer[:current_write_idx].copy()",
    "                    ))",
    "            ",
    "            if len(new_samples.shape) > 1:",
    "                new_samples = new_samples.flatten()",
    "                ",
    "            last_read_idx = current_write_idx",
    "            local_audio_buffer = np.concatenate((local_audio_buffer, new_samples))",
    "",
    "            if len(new_samples) > 0:",
    "                rms = np.sqrt(np.mean(np.square(new_samples)))",
    "                fft_vals = np.abs(np.fft.rfft(new_samples))",
    "                bands = np.array_split(fft_vals, 12)",
    "                cur_bands = np.array([np.log1p(np.mean(b)) if len(b) > 0 else 0 for b in bands])",
    "                self._fft_ema_bands = 0.7 * self._fft_ema_bands + 0.3 * cur_bands",
    "                ",
    "                if not in_speech:",
    "                    self.bus.publish('voice_events', 'MIC_AMPLITUDE', {",
   
